version: '3'

services:
  db:
    image: mysql:5.6
    container_name : ffxivbot-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: FFXIV_DEV
    volumes:
      - ./docker/mysql-data:/var/lib/mysql
    networks:
      - ffxivbot_network
  web:
    container_name : ffxivbot-web
    image: 'bluefissure/ffxivbot:latest'
    build: .
    depends_on:
      - db
      - redis
      - migration
    networks:
      - ffxivbot_network
    ports:
      - 8000:8002
    restart: always
    command: daphne FFXIVBOT.asgi:application -b 0.0.0.0 -p 8002
  redis:
    container_name : ffxivbot-redis
    image: "redis:alpine"
    networks:
      - ffxivbot_network
  migration:
    container_name : ffxivbot-web-migration
    image: 'bluefissure/ffxivbot:latest'
    command: bash -c "python manage.py migrate && python manage.py collectstatic" 
    restart: on-failure
    depends_on:
      - db
    networks:
      - ffxivbot_network
networks:
  ffxivbot_network:
volumes:
  mysql-data:
