version: '3'

services:
  db:
    image: mysql:5.6
    container_name : ffxivbot-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: FFXIV_DEV
    volumes:
      - ./docker/mysql-data:/var/lib/mysql
    networks:
      - ffxivbot_network
  web:
    container_name : ffxivbot-web
    build: .
    volumes:
      - .:/FFXIVBOT
    depends_on:
      - db
    networks:
      - ffxivbot_network
    ports:
      - 8000:8002
    working_dir: /FFXIVBOT
    command: daphne FFXIVBOT.asgi:application -b 0.0.0.0 -p 8002
  # nginx:
  #   image: nginx
  #   restart: always
  #   container_name : sspanel-nginx
  #   volumes:
  #     - ./configs/nginx/:/etc/nginx/conf.d
  #     - static:/src/FFXIVBOT/static
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - web
  #   networks:
  #     - ffxivbot_network
  redis:
    image: "redis:alpine"
    networks:
      - ffxivbot_network
networks:
  ffxivbot_network:
volumes:
  static:
  mysql-data: