version: '3'

services:
  db:
    image: mysql:5.6
    container_name : ffxivbot-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: FFXIV_DEV
    volumes:
      - ./docker/mysql-data:/var/lib/mysql
      - ./docker/mysql-dump:/mysql-dump
    networks:
      - ffxivbot_network
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  web:
    container_name : ffxivbot-web
    image: 'bluefissure/ffxivbot:latest'
    depends_on:
      - db
      - redis
    environment:
      QQ_BASE_URL: http://111.231.102.248/
      TULING_API_KEY: TULING_API_KEY
    networks:
      - ffxivbot_network
    ports:
      - 8000:8002
    restart: always
    command: daphne FFXIVBOT.asgi:application -b 0.0.0.0 -p 8002
  redis:
    container_name : ffxivbot-redis
    image: "redis:alpine"
    networks:
      - ffxivbot_network
networks:
  ffxivbot_network:
volumes:
  mysql-data:
  mysql-dump:
